### ISSUE TITLE
react-datetime module problem

### ISSUE THREAD

**Issue by michaelnlindsay** [dtrelogan/react-formstate#1]
Hello, This isn't an issue with react-formstate per se, i've tried a couple of other form libraries and this one has the most flexible and easy implementation I've seen so far for wiring up validation.  In the project I'm working on we're using [react-datepicker](https://github.com/Hacker0x01/react-datepicker), it's return value is a [moment](http://momentjs.com/) not an event, so the built in event handler chokes looking for e.target.type.  I'm sure there's a clever way around this, but I haven't been able to crack it.  

I tried using my own onChange handler, converting moment to string and attempting to update the state: 
this.props.fieldState.setValue(dateString); // Cannot update a read-only field state

Then tried updating the form state state and get the same error as I would without my own handler:
updatedValue[this.props.formField] = dateString;
this.props.updateFormState(updatedValue); // Cannot read property 'type' of undefined

I'm thinking I may have to pass the context into my component from the form to get something writeable, or creating and dispatching my own event object, but I'm really fishing here.

Any suggestions?

**Comment by dtrelogan** [comment]
hi. thanks for the feedback!

my first thought is to suggest checking out the [asynchronous validation](https://github.com/dtrelogan/react-formstate/blob/master/docs/asyncExample.md) example for how to override the standard event handler. form state updates need to proceed through a "unit of work" which is the package's solution to updating immutable state. typically you'd define the handler in the form component such that you'd have a reference to "this.formState" and then provide the handler to the date picker component somehow. the gist:

```jsx
handleDatePickerChange(dateString) {
    let context = this.formState.createUnitOfWork(),
      fieldState = context.getFieldState('yourDateFieldName');

    fieldState.setValue(dateString);
    fieldState.validate();
    context.updateFormState();
}
```

let me know if that helps. maybe you've already gotten that far?

**Comment by dtrelogan** [comment]
i found some time tonight and played around with react-datepicker. i was trying to respond quickly but it looks like i gave you flawed advice.

coercing the moment to a string seems to cause problems so it's best to use react-formstate's 'noCoercion' feature.

also, you need to take care to use the prop name 'updateFormState' for the custom handler.

i got the following working:

```jsx
import React from 'react';
import DatePicker from 'react-datepicker';
import moment from 'moment';

export default class MyDatePickerLayout extends React.Component {
  render() {
    return (
      <div>
        <label>{this.props.label}</label>
        <DatePicker
          selected={this.props.fieldState.getValue()}
          onChange={this.props.updateFormState}
          />
        <span>{this.props.fieldState.getMessage()}</span>
      </div>
    )
  }
}
```

```jsx
  render() {
    return (
      <Form formState={this.formState}>
        <MyDatePickerLayout
          formField='when'
          label='When'
          updateFormState={this.handleDatePickerChange.bind(this)}
          defaultValue={moment()}
          noCoercion
          />
        <input type='submit' value='Submit' onClick={this.submit}/>
      </Form>
    );
  }

  handleDatePickerChange(newMoment) {
    let context = this.formState.createUnitOfWork(),
      fieldState = context.getFieldState('when');

    fieldState.setValue(newMoment);
    fieldState.validate();
    context.updateFormState();
  }

  submit(e) {
    e.preventDefault();
    let model = this.formState.createUnitOfWork().createModel();
    if (model) {
      alert(JSON.stringify(model));
    }
  }
```

**Comment by dtrelogan** [comment]
hi, i posted a couple responses directly on github. not sure if you got
them. i'm going to close the ticket tomorrow if i haven't heard from you by
then. i have a potential enhancement in mind that could potentially improve
the package. let me know if you are still interested.

thanks again for the feedback.

**Comment by michaelnlindsay** [comment]
Hey, Thanks for your quick reply.  Had a long weekend off the grid, but
I'll try to implement your recommendations today.

**Comment by michaelnlindsay** [comment]
That did the trick!  Thanks for your help!

**Comment by dtrelogan** [comment]
glad to hear it.

fyi, today i pushed a [new feature](https://github.com/dtrelogan/react-formstate/blob/master/docs/datePickerExample.md) that attempts to streamline the work involved for your use case. it's not quite the ideal solution but nevertheless i think it could save you some busy work.

thanks again.

**Comment by michaelnlindsay** [comment]
Awesome, and thank you.  I like option 3 as it keeps that date logic in the component.  Nice work.

**Comment by michaelnlindsay** [comment]
FYI, used opt 3 shim method and am very happy with the results, all date handling now in the component :D

**Comment by dtrelogan** [comment]
happy to hear it!

**Comment by dtrelogan** [comment]
michael,

hi. i [refactored react-formstate](https://github.com/dtrelogan/react-formstate/blob/master/docs/api.md#the-updateformstate-handler) a little and arrived at a better solution for your react-datepicker requirement than passing a shimmed event to the default event handler.

if you are still using react-formstate, you might want to consider refactoring to the new handleValueChange handler. of course you don't have to but i think it'd be worth the minimal effort required.

thanks again for your prior interest in the project!

**Comment by dtrelogan** [comment]
oh and just want to point out in addition to new handleValueChange prop you can remove the 'noCoercion' prop and instead use getUncoercedValue in your component. much cleaner...

hopefully the example made that clear but want to be sure.
