### ISSUE TITLE
Lack of user interest

### ISSUE THREAD

**Issue by dtrelogan** [dtrelogan/react-formstate#10]
>> After a year and a half on NPM, looking at overall downloads and GitHub stars, this package has received lukewarm response at best, which is fine, if it deserves it. The thing I get stuck on, is when I analyze this package and compare it to alternative packages, I keep coming up with a favorable picture of this one, which is why I threw so much into trying to make it accessible and available to the community. So I'm curious to understand, in the eyes of the React community, how this is coming up short. If you are willing to provide feedback [here] you'd be helping me out a great deal. Thanks.

...

This project was an attempt to give back to the open source community (and to fill a gap in React for my own personal projects). I stand to make no money on this endeavor. So if it's a marketing issue, it's not like I'm going to start advertising the thing. However, if it's an issue with the technical quality or appearance of the package, that's something I'd be curious to learn about. (I may or may not be able to fix any issues, but at least I'd know what they are.)

My best guesses for why this has struggled to gain adoption (other than not enough eyes on the thing) are 1) lack of trust, and 2) most forms are served by simpler, less robust packages. So, while this package has its advantages, most people don't notice them or maybe see it as overwrought (whereas I see other packages as brittle).

But I'm searching here, hence the request for feedback. Thanks...

**Comment by devanandb** [comment]
I don't know about others, but personally I love your work and this package, have not seen any other even close to it, and it is used in a huge enterprise HPE (now Microfocus) projects extensively!

And again on a personal level @dtrelogan you have been very helpful! I am doing part to publicize and make people use this whenever I can!

Thanks again,
Dev

**Comment by dtrelogan** [comment]
Thanks, devananddb. I _really_ appreciate it. Glad to hear you and HPE are still around and happy with it. It's been about a year since I've heard so much as a peep from anyone on this project and it's not unusual where it goes a week without a single download. I suppose it just got really... lonely... working on this thing. Maybe I can look on the bright side and chalk up the lack of chatter to the package being well-built and bug-free (I kid... I kid...)

Per your comment, I suppose I would also be interested to learn what someone other than myself might *like* about this project, and maybe I should simply STFU and be happy about it. At the same time, while HPE using the thing is **awesome**, considering that something like redux-form gets downloaded 100K times a week, five GitHub stars and going an entire week without a single download (a download that I can't account for that is), that ain't great. Things need to get used otherwise they die.

Regardless, can't tell you how much I appreciate your feedback, support, and message of encouragement. Thanks.

**Comment by dtrelogan** [comment]
Devananddb, a year later I suspect you and I are still effectively the user base of react-formstate. I think I've done as much as I can to improve the package technically, and to make it as accessible and approachable as possible. I think broadening the user base would require marketing the package somehow, but I don't know if I'm up for that. I wouldn't know where to begin, honestly. That being said, it's certainly not up to you to fill that gap. Thanks for all you've done.

My instinct is this package is one of the best on NPM for React forms and people are missing out, but I'm not an objective observer and I don't know that for certain.

If there are lurkers out there, I believe starring the react-formstate packages on GitHub and NPM helps them show more prominently in search results on those sites. I believe that's the only way to find this thing.

In the meantime, Devananddb, the package's viability outside of my own personal use seems to be founded on HPE's adoption. You're right that I should be happy about that. Glad to have you here. If you need anything let me know.

Also, if you started manufacturing a bunch of downloads as a result of this episode, I appreciate the gesture, but totally not necessary.
