### ISSUE TITLE
Example for textarea?

### ISSUE THREAD

**Issue by devanandb** [dtrelogan/react-formstate#2]
Can you please provide a component example for textarea?

**Comment by dtrelogan** [comment]
good call, i will add an example this week.

in the meantime, if you take a look at this
https://facebook.github.io/react/docs/forms.html#why-textarea-value

using that i'd think it would follow along the lines of the other examples.

**Comment by devanandb** [comment]
Yup, I figured that out yesterday, thanks though for a great library!

I know I am asking for a lot but it would be great if there is a UI with examples.

**Comment by dtrelogan** [comment]
yeah i think redux forms has something like that in its documentation. i agree it'd be really nice to have but i can't commit to getting that done at the moment.

glad you figured out text area. i still plan to add an example per your suggestion.

thanks for the feedback!
