### ISSUE TITLE
Getting errors when loading in dev server

### ISSUE THREAD

**Issue by devanandb** [dtrelogan/react-formstate#6]
Hey there!

Am getting these errors on dev server.

Warning: Unknown props `formObject`, `formState`, `validationComponent`, `labelPrefix` on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop

Any clue?

**Comment by dtrelogan** [comment]
sounds to me like you are trying to place those on a plain old html tag rather than a component designed to work with react-formstate, e.g.:

```jsx
<input formField='fieldName' ... />
```

vs

```jsx
<Input formField='fieldName' ... />
```
but without seeing your code i'm just guessing. any which way this does not sound like an issue with react-formstate.

**Comment by dtrelogan** [comment]
hey i'm going to go ahead and close this

**Comment by devanandb** [comment]
Hey there, 

Thanks for the amazing library, I could everything working! so its all great now, would love to show  the form I was trying to build!

I am still getting those errors though, 

referring to different issue the other library was facing too:

https://github.com/rkit/react-select2-wrapper/issues/39

Can you please check?

<img width="1504" alt="screen shot 2016-08-11 at 3 42 48 am" src="https://cloud.githubusercontent.com/assets/1044609/17586322/d8acb774-5f75-11e6-9659-9d1ec62385a3.png">

**Comment by dtrelogan** [comment]
i updated the tests to use react and react-dom 15.3 and did not encounter the issue. i will upgrade my project with the more complex forms and see if i run into this.

**Comment by dtrelogan** [comment]
i haven't been able to reproduce the problem you're having. with the new version of react i've seen some of these warnings wrt react-bootstrap components but none of the issues have been related to react-formstate
